google/capslock

- docs/README.md
When viewing in github's source view, the link from README.md to capabilities documentation takes you to https://github.com/google/capslock/blob/main/docs/docs/capabilities.md which does not exist.
> Fix link to capabilities in README.md

- analyzer/analyzer.go
- cmd/capslock/capslock.go
- interesting/interesting.go
- interesting/interesting_test.go
This implements the ability to specify a custom capability mapping file, using the same format as `interesting/interesting.cm`. This file may be used to override the default capabilities (e.g. to mark things that the user isn't worried about as `CAPABILITY_SAFE`) but can also be used in place of the the default capability map entirely.
Example session:
```shell
$ # Create a custom capability map.
$ echo "package os/exec CAPABILITY_SAFE" > /tmp/custom.cm
$ ./capslock > /tmp/a
2023/08/25 14:15:42 Loaded package "main"
$ # Use the custom capability map.
$ ./capslock --capability_map=/tmp/custom.cm > /tmp/b 
2023/08/25 14:15:44 Using custom capability map "/tmp/custom.cm"
2023/08/25 14:15:44 Loaded package "main"
$ diff -u /tmp/a /tmp/b
--- /tmp/a	2023-08-25 14:15:44.195909367 +1000
+++ …
```
> Bring-your-own capability mappings

- cmd/capslock/capslock.go
The packageNames slice will never be empty.  If the flag -packages is empty, packageNames will contain the empty string, and the package in the current directory will be analyzed.
Fixes #28
> Remove if statement whose condition is always false.

- analyzer/analyzer.go
- testing/analyzepackages_test.go
- testpkgs/useunsafe/useunsafe.go
Previously we went package-by-package and iterated through (ssa.Package).Members, but this only contains functions, not methods.  Instead we iterate through the result of ssautil.AllFunctions.
Add test cases for a package-level variable whose initialization expression converts an unsafe pointer to *int, and a method which does the same.
> Find all methods that use unsafe pointers.

- README.md
- docs/capabilities.md
- docs/examples.md
Also, fix example use of -output=json flag.
> docs: fix a few typos (Caplock -> Capslock)

- analyzer/compare.go
- analyzer/graph.go
- analyzer/scan.go
- analyzer/util.go
This moves some disparate parts out of scan.go into {compare,graph}.go.
> Reorganize the code under analyzer/.

- analyzer/load.go
- cmd/capslock/capslock.go
This results in all the loaded source being stored in a single token.FileSet.  Without this, we couldn't look up line numbers correctly if there was more than one package pattern specified on the command line.
> analyzer: use a single call to packages.Load for all packages

- analyzer/analyzer.go
- analyzer/analyzer_test.go
- analyzer/compare.go
- analyzer/graph.go
- analyzer/scan.go
- cmd/capslock/capslock.go
When the disable_builtin flag is set with a custom classifier, default capabilities should not be added.
> Make Capslock respect custom capability mappings.

- analyzer/analyzer.go
- analyzer/scan.go
- analyzer/util.go
While the choice of call path the tool displays to demonstrate why a function has a particular capability is somewhat arbitrary, it's useful if the choice is consistent across runs so that outputs can be compared more easily.
To achieve this, we add sorts in various places, and improve the existing sorts for graph nodes and edges so there are no spurious ties between items.
> analyzer: add determinism for various output modes

- analyzer/rewrite.go
- testpkgs/rewrites/rewrites.go
The rewriteCallsToSort function uses astutil.Apply to modify the AST.  These modifications replace single statements with multiple statements, but this is not valid in all parts of the syntax tree, e.g. the init part of a for statement.  So here we check the context of a statement before rewriting it.
> analyzer: fix some cases of incorrect AST rewriting

- go.mod
- go.sum
This picks up some fixes added since the last version tag of x/tools.
> go.mod: depend on latest commit of golang.org/x/tools

- docs/capabilities.md
- interesting/interesting.go
The PR corrects a typo in the documentation and the comment.
> docs: fix typos

- analyzer/analyzer.go
- analyzer/util.go
Using a pointer receiver reduces the number of visitor structs that need to be allocated when creating ast.Visitor values.
> analyzer: optimize visitor.Visit

- analyzer/analyzer.go
- analyzer/analyzer_test.go
- interesting/interesting.go
This is simpler than having each callsite extract the caller and callee.  This fixes one callsite where this was done incorrectly.
Add more tests to analyzer_test.
> analyzer: change IncludeCall to take a *callgraph.Edge

- analyzer/analyzer.go
- analyzer/compare.go
- analyzer/scan.go
- cmd/capslock/capslock.go
- testing/analyzepackages_test.go
Change compare to return its result to the caller rather than exiting the program on its own.
Add example stack traces to diff reports.
Add a "granularity" option that determines whether capabilities are compared for each package or each function.
Add some more tests.
> analyzer: some changes to the comparison code

- analyzer/analyzer.go
- analyzer/analyzer_test.go
- analyzer/graph.go
- analyzer/util.go
Change the outputCall parameter of CapabilityGraph to include, alongside the callgraph edge, the BFS tree that led from the query to the edge's caller, and from the edge's callee to a capability.  Users of CapabilityGraph can use this information to reconstruct an example call path through the graph that includes the given edge.
Add a type definition for the BFS state, since it is repeated frequently.
Add types for the two callback function parameters of CapabilityGraph.
Make the search order for graph output deterministic, by considering edges in sorted order when visiting a node.  This is similar to what is done for other output modes.
Add a byCallee type, similar to the byCaller type, for sorting callgraph edges by their callee.
> analyzer: some changes to call graph generation

- analyzer/analyzer.go
- analyzer/analyzer_test.go
- analyzer/graph.go
- cmd/capslock/capslock.go
- testing/analyzepackages_test.go
Setting -capabilities to e.g. "NETWORK" or "-UNSAFE" will specify capabilities to include or exclude from the output graph.
Adds a parameter to analyzer.CapabilityGraph to do this filtering.
> cmd/capslock: add a flag to limit capabilities in graph output

- interesting/interesting.cm
Classifies more internal functions in several packages and adds some ignored callgraph edges.
Classifies x/sys/cpu as safe.
Fixes classification of os.Expand, which calls one of its parameters.
Adds the new function _Cgo_no_callback to the list of functions that are generated by cgo.
> interesting: new function classifications

- go.mod
- go.sum
This commit includes some bug fixes relevant to Capslock.
> go.mod: depend on a newer commit of x/tools

- analyzer/graph.go
- testing/analyzepackages_test.go
Previously, an empty graph would be written as just "}".
> analyzer: fix DOT output for empty graphs

- go.mod
- interesting/interesting.go
Use the new maps and slices packages to simplify the classifier merging code.
> go.mod: upgrade Go version to 1.21

- analyzer/analyzer.go
- analyzer/analyzer_test.go
- analyzer/compare.go
- analyzer/graph.go
- cmd/capslock/capslock.go
Adds GranularityFromString and NewCapabilitySet functions for creating
these from command-line flags or other strings.
This simplifies the code, and allows callers of the library to validate
strings before calling more expensive setup functions.
We allow "" as a valid granularity, to indicate the default granularity
for the operation.
> analyzer: make exported types Granularity and CapabilitySet

- analyzer/analyzer.go
- analyzer/analyzer_test.go
- analyzer/compare.go
Setting --granularity=function, or leaving granularity unset, gives the
existing behavior.
For --granularity=package, the returned list is pruned so that there is
only one entry per (capability, queried package) pair.
We also add a new option, --granularity=intermediate.  This granularity
finds which packages exist anywhere along a path in the callgraph from a
function in a queried package to a function with a capability.
This allows users to see when a change in their dependencies results in
a capability being reached in a path via a new package, even if the
top-level function already had that capability through another path.
> analyzer: support the granularity flag with --output=json

- interesting/interesting.cm
Classify some functions in net, net/http, runtime, protobuf, os/exec, runtime/pprof. internal/chacha8rand.  Classify the package "unique" as safe.
Change the classification of net.OpError methods to UNSPECIFIED since they call methods on an interface field that can have an arbitrary type.
> interesting: add more function classifications

- analyzer/util.go
- go.mod
Also updates analyzer.containsReflectValue to handle the new go/types.Alias type.
> go.mod: upgrade Go version to 1.23.3

- analyzer/util.go
Passing nil as the "initial" argument of vta.CallGraph uses the new internal version of the cha algorithm which stores its output graph implicitly.  This saves time and memory for large callgraphs.
> analyzer: use the memory-optimized version of CHA

- cmd/capslock/capslock.go
If the packages the user requested are not dependencies of the current workspace, then loading of those packages will fail.  In those cases, this change makes capslock switch to a temporary module, use `go get` to add the requested packages as dependencies, and try the analysis again.
Fixes #200
> cmd/capslock: allow analysis of non-dependencies

- analyzer/analyzer.go
- analyzer/analyzer_test.go
- analyzer/static/verbose.tmpl
- cmd/capslock/capslock.go
The example call paths can use a lot of space.  This change adds an option to omit them.
In the json output, when granularity=function, the function is still included as the first element of the path.
> analyzer: add option to omit example call paths

- cmd/capslock/capslock.go
- testing/analyzepackages_test.go
Outputs version numbers of the code that most affects the analysis.
It uses the build information embedded in the executable to print the version of capslock, the version of the Go toolchain, and the version of the golang.org/x/tools module used.
Fixes #267
> cmd/capslock: add -version flag
